#!/usr/bin/env python

import os
from subprocess import call

try:
    user, passwd = os.environ.get("BASIC_AUTH", '').split(':')
except:
    print "No valid user/passwd setings found in $BASIC_AUTH. Skipping.."
else:
    print "---> Configuring apache  basic auth"
    call(["htpasswd", "-b", "-c", "/etc/apache2/basic-access",
            user, passwd])
    call(["envtpl", "/etc/apache2/conf-available/basic-auth.conf.tpl",
            "--allow-missing"])
    call(["a2enconf", "basic-auth"])
    print "apache basic auth done."
